# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run tests"
  lane :test do
    scan(
      scheme: "SportCrunch",
      destination: "platform=iOS Simulator,name=iPhone 17"
    )
  end

  desc "Deploy to Internal Testers on TestFlight"
  lane :deploy_internal do
    increment_build_number(xcodeproj: "SportCrunch.xcodeproj")
    build_app(scheme: "SportCrunch")
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end

  desc "Deploy to External Testers on TestFlight"
  lane :deploy_external do
    increment_build_number(xcodeproj: "SportCrunch.xcodeproj")
    build_app(scheme: "SportCrunch")
    upload_to_testflight(
      distribute_external: true,
      skip_waiting_for_build_processing: true
    )
  end
end
